name: flutter_easyloading
description: A clean and lightweight 
version: 3.0.5
homepage: https://github.com/nslogx/flutter_easyloading

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
